// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Models
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> NEWSIDAsync(string TableName, OutputParameter<string> ReturnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_Delete_ACPDAsync(string acpd_sid, string acpd_updid, OutputParameter<string> OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_Insert_ACPDResult>> usp_Insert_ACPDAsync(string acpd_cname, string acpd_ename, string acpd_sname, string acpd_email, byte? acpd_status, bool? acpd_stop, string acpd_stopMemo, string acpd_LoginID, string acpd_LoginPW, string acpd_memo, string appd_nowid, OutputParameter<string> OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_Update_ACPDAsync(string acpd_sid, string acpd_cname, string acpd_ename, string acpd_sname, string acpd_email, byte? acpd_status, bool? acpd_stop, string acpd_stopMemo, string acpd_LoginID, string acpd_LoginPW, string acpd_memo, string acpd_updid, OutputParameter<string> OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
